/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ChatList from "./ChatList";

const ChatListContainer: React.FC = () => {
  const todayChats = [
    {
      name: "نورة بنجلون",
      message: "حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى",
      time: "19:15",
      isRead: true,
      isToday:true,

    },
    {
      name: "محمد الراشد",
      message: "حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى",
      time: "04:54",
      isRead: false,
      isToday:true,

    },
    {
      name: "عمر الفاروق",
      message: "حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى",
      time: "02:30",
      isRead: true,
      isToday:false,

    },
    {
      name: "ليلى القاضي",
      message: "حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى",
      time: "10:00",
      isRead: false,
      isToday:false,

    },
  ];

  const yesterdayChats = [
    {
      name: "أحمد المنصوري",
      message: "حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى",
      time: "12:00",
      isRead: false,
      isToday:false,
    },
    {
      name: "زينب العمراني",
      message: "حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى",
      time: "08:00",
      isRead: true,
      isToday:true,

    },
    {
      name: "كريم المرابطي",
      message: "حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى",
      time: "03:00",
      isRead: false,
      isToday:false,
    },
    {
      name: "أحمد المنصوري",
      message: "حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى",
      time: "11:00",
      isRead: false,
      isToday:false,

    },
    {
      name: "فاطمة الحربي",
      message: "حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى",
      time: "03:00",
      isRead: false,
      isToday:false,

    },
  ];

  return <ChatList todayChats={todayChats} yesterdayChats={yesterdayChats} />;
};

export default ChatListContainer;
