/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ChatListItem from "./ChatListItem";

interface ChatData {
  name: string;
  message: string;
  time: string;
  isRead: boolean;
  isToday: boolean;
}

interface ChatListProps {
  todayChats: ChatData[];
  yesterdayChats: ChatData[];
}

const ChatList: React.FC<ChatListProps> = ({ todayChats, yesterdayChats }) => {
  return (
    <section className="flex flex-col text-base">
      <h2 className="w-full font-semibold tracking-wide leading-[150%] text-slate-500 max-md:max-w-full">
        اليوم
      </h2>
      {todayChats.map((chat, index) => (
        <ChatListItem key={`today-${index}`} {...chat} isToday={true} />
      ))}
      <h2 className="mt-8 w-full font-semibold tracking-wide leading-[150%] text-slate-500 max-md:max-w-full">
        الأمس
      </h2>
      {yesterdayChats.map((chat, index) => (
        <ChatListItem key={`yesterday-${index}`} {...chat} isToday={false} />
      ))}
    </section>
  );
};

export default ChatList;
