/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ChatListItemProps {
  name: string;
  message: string;
  time: string;
  isRead: boolean;
  isToday: boolean;
}

const ChatListItem: React.FC<ChatListItemProps> = ({
  name,
  message,
  time,
  isRead,
  isToday,
}) => {
  return (
    <article
      className={`flex gap-5 justify-between px-4 py-5 w-full rounded-xl ${
        isRead ? "bg-slate-50" : "bg-white"
      } max-md:flex-wrap max-md:max-w-full`}
    >
      <div className="flex gap-5 my-auto tracking-wide leading-[150%] max-md:flex-wrap max-md:max-w-full">
        {isRead ? (
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a83e14e500aecc281241eff4536648fc29ba720b6039169e31684e3adaad06a9?apiKey=85058072149448d6b350b930168b1cb5&&apiKey=85058072149448d6b350b930168b1cb5"
            className="shrink-0 w-5 aspect-square"
            alt=""
          />
        ) : (
          <div className="shrink-0 w-5 h-5 rounded border border-solid border-slate-200" />
        )}
        <h3 className="font-semibold text-slate-900">{name}</h3>
        <p className="flex-auto font-medium text-slate-500">{message}</p>
      </div>
      <div className="flex gap-5 justify-between text-right whitespace-nowrap leading-[160%] text-slate-500">
        {isToday && (
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/6c4ead497d07720c02eb137beb8b2cd4e8884ea9194fadcaf838405168f2a3f4?apiKey=85058072149448d6b350b930168b1cb5&&apiKey=85058072149448d6b350b930168b1cb5"
            className="shrink-0 w-6 aspect-square"
            alt=""
          />
        )}
        <time className="my-auto">{time}</time>
      </div>
    </article>
  );
};

export default ChatListItem;
