// app/layout.tsx
import { Inter } from '@next/font/google';
import './globals.css';
import { UserProvider } from './context/UserContext'; // Adjusted path

const inter = Inter({
  subsets: ['latin'],
  weight: ['200', '300', '400', '700', '800', '900'],
  display: 'swap',
});

export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="font-zain">
      <body className={inter.className}>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
