/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface FormFieldProps {
  label: string;
  placeholder: string;
  value: string;
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  icon?: string;
}

const FormField: React.FC<FormFieldProps> = ({
  label,
  placeholder,
  value,
  onChange,
  icon,
}) => {
  return (
    <div className="mb-6">
      <label className="text-sm font-bold leading-6 text-slate-900 block mb-2">
        {label}
      </label>
      <div className="flex gap-3 px-4 py-2 text-base tracking-wide rounded-xl border border-solid border-slate-200 text-stone-300">
        <input
          type="text"
          placeholder={placeholder}
          value={value}
          onChange={onChange}
          className="flex-1 bg-transparent outline-none"
        />
        {icon && (
          <img
            loading="lazy"
            src={icon}
            alt=""
            className="shrink-0 my-auto w-5 aspect-square"
          />
        )}
      </div>
    </div>
  );
};

export default FormField;
