/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="text-right mb-6">
      <h1 className="text-2xl font-bold tracking-wide text-slate-900">
        تسجيل الدخول
      </h1>
      <p className="mt-3 text-sm leading-6 text-slate-500">
        المرجو إدخال البريد الإلكتروني و كلمة السر
      </p>
    </header>
  );
};

export default Header;

