/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ImageSection: React.FC = () => {
  return (
    <section className="flex flex-col w-[100%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow items-center px-14 py-16 w-full bg-blue-600 max-md:px-5 max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-3 self-start text-2xl font-bold tracking-tight text-white whitespace-nowrap">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/bfc38da10a699dd0e42d43f6322e2a57dc0948f4463ef94de58669cc4c31f170?apiKey=85058072149448d6b350b930168b1cb5&&apiKey=85058072149448d6b350b930168b1cb5"
            alt=""
            className="shrink-0 aspect-square fill-white w-[33px]"
          />
          <div className="flex-auto">Hiphonic</div>
        </div>
        <div className="flex flex-col self-end px-16 pt-20 pb-9 mr-6 max-w-full rounded-full w-[424px] max-md:px-5 max-md:mt-10 max-md:mr-2.5 mr-20 ">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/8f594ceaea28caa5cc384e197e54e682cb9d9f8323b7b60a3229b6db358fecc0?apiKey=85058072149448d6b350b930168b1cb5&&apiKey=85058072149448d6b350b930168b1cb5"
            alt="Hiphonic app interface"
            className="mr-5 ml-5 w-full  aspect-[0.89] max-md:mx-2.5"
          />
        </div>
        <h2 className="mt-12 text-2xl font-bold tracking-wide text-center text-white max-md:mt-10">
          دير الإشهار ديالك دابا بكل سهولة...
        </h2>
        <p className="mt-3  text-sm leading-6 text-center text-slate-50">
          بنقرة واحدة الإشهار يوصل لجميع المستمعين
        </p>
        <div className="flex gap-4 pr-2.5 mt-10 ">
          {[1, 2, 3].map((_, index) => (
            <div
              key={index}
              className="shrink-0 w-2.5 h-2.5 bg-white rounded-full"
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default ImageSection;
