/**
 * This code was generated by Builder.io.
 */
import React from "react";
import AudioPlayer from "./AudioPlayer";

interface AudioUploadProps {
  label: string;
}

const AudioUpload: React.FC<AudioUploadProps> = ({ label }) => {
  return (
    <div className="mb-6">
      <label className="text-sm font-bold leading-6 text-slate-900 block mb-2">
        {label}
      </label>
      <div className="flex gap-5 mt-6 max-md:flex-wrap">
        <AudioPlayer />
        <button className="flex-auto my-auto text-sm font-bold leading-6 underline text-slate-500">
          <span className="underline">تغيير الملف الصوتي</span>
        </button>
      </div>
    </div>
  );
};

export default AudioUpload;
