/**
 * This code was generated by Builder.io.
 */
"use client";
import React from "react";
import { useRouter } from "next/navigation"; // Import the router

const Logo: React.FC = () => {
  const router = useRouter(); // Use router for navigation

  const goToHome = () => {

    // Redirect to homepage
    router.push("/");
  };
  return (
    <div className="flex gap-4 self-center text-2xl font-bold tracking-tight whitespace-nowrap text-slate-900">
     
      <div className="flex gap-2.5 pr-5">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/c579f2ebd4b19aadd9b2f72edf4cd7da8640c4d7c0e433ffd61abb19f0e3ae59?apiKey=85058072149448d6b350b930168b1cb5&&apiKey=85058072149448d6b350b930168b1cb5"
          alt=""
          className="shrink-0 w-7 aspect-[1.04] fill-blue-600"
        />
        <div  className="text-xl font-bold text-slate-900 cursor-pointer"
          onClick={goToHome}>Hiphonic</div>
        
      </div>
    </div>
  );
};

export default Logo;
