/**
 * This code was generated by Builder.io.
 */
import React from "react";

const LanguageSelector: React.FC = () => {
  return (
    <div className="flex gap-3 self-start mt-5 whitespace-nowrap">
      <div>عربي</div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/c20d95fc20625f58bbca4a04fef458076ee51d9942025bcbffd6f71d963fbf71?apiKey=85058072149448d6b350b930168b1cb5&&apiKey=85058072149448d6b350b930168b1cb5"
        alt=""
        className="shrink-0 self-start border border-gray-800 border-solid aspect-[1.79] stroke-[1px] stroke-gray-800 w-[9px]"
      />
    </div>
  );
};

export default LanguageSelector;
